apiVersion: v1
kind: Template
metadata:
  name: python-plus-job
  annotations:
    description: "Template to create a buildconfig for adding to the s2i python builder image."
    tags: "python,quickstart"
labels:
  template: ${{JOB_NAME}}
  ${{TEMPLATE_NAME}}: augmented

objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: $${{JOB_NAME}}
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: ${{JOB_NAME}}
      spec:
        containers:
        - name: ${{IMAGE_NAME}}
          image: 
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        restartPolicy: OnFailure    
  parameters:
  - name: JOB_NAME
    description: The name to associate with this job
    required: true
  - name: IMAGE_NAME
    description: The name of the image to run
    value: python-plus-image
